# 不能使用Tab退格键
# k:(空格)v  -- 必须要有空格

# debug:
#  true

server:
  port: 8888
  
spring:
  profiles:
    active: prod

logging:
  level:
    com: 
      zhangchao: warn
  file: springboot.log

# 测试读取配置文件的值  ${random.value} ${random.int} ${random.value}
person:
  last-name: zhangsan${random.uuid}
  age: 12
  birth: 2017/12/15
  boss: false
  maps: {k1: v1,k2: 14}
  lists:
    - a
    - b
    - c
  dog:
    name: dog
    age: 15
    

---
server:
  port: 8083
spring:
  profiles: dev

---
server:
  port: 8084
spring:
  profiles: prod